name: Build and deploy Node.js app to Azure Web App - nutrifacil-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          # Remove devDependencies e cache
          npm prune --production

      - name: Check installed packages
        run: npm list dotenv  # Verifica se o dotenv está instalado

      - name: Zip artifact for deployment
        run: |
          # Cria zip apenas com os arquivos necessários
          zip -r release.zip . -x '*.git*' '*.github*' 'node_modules/*' 'release.zip'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCC66B2C0ADF4A518FEC05D3B8A5417C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5282486849C14465B24B3F8B5B81F26D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F64F5E0B63CE4D67ACBB2E9BFF613B20 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutrifacil-back'
          slot-name: 'Production'
          package: .
          clean: true  # Limpa o diretório antes do deploy